baseURL = "http://mtinone.com"
languageCode = "en-us"
title = "Marina Tinone"
copyright = "Marina Tinone"
theme = "cactus"
pluralizeListTitles = "false"

[[menu.main]]
name = "About"
url = "/about"
weight = 1

[[menu.main]]
name = "Portfolio"
url = "/portfolio"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

[params]
  description = "Marina writes about youth, memory, and responsibility."
  mainSection = "portfolio"
  showAllPostsOnHomePage = false
  postsOnHomePage = 5
  showProjectsList = false
  rss = true

[[params.social]]
  name = "ko-fi"
  link = "https://ko-fi.com/mtinone"

[[params.social]]
  name = "instagram"
  link = "https://instagram.com/mtinone"
 
[[params.social]]
  name = "buttondown"
  link = "https://buttondown.email/mtinone" 
